model_name_or_path: /data1/hcc/deepresearch/Dee/model/Qwen3-1.7B
trust_remote_code: true
flash_attn: fa2
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: all
deepspeed: /data1/hcc/LlamaFactory/examples/deepspeed/ds_z2_config.json
dataset_dir: /data1/hcc/deepresearch/Dee/results/76_w5_controller_dataset
dataset: w5_controller_train
eval_dataset: w5_controller_dev
template: qwen3_nothink
enable_thinking: false
cutoff_len: 4096
train_on_prompt: false
mask_history: true
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 8
output_dir: /data1/hcc/deepresearch/Dee/outputs/77_w5_controller_lora
logging_steps: 1
save_steps: 100
save_total_limit: 2
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: tensorboard
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
optim: adamw_torch_fused
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
seed: 42
resume_from_checkpoint: null
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50
